apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName | quote }}
  namespace: {{ .Values.namespaceName | quote }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::892893225782:role/aws-node"
